import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ScrollToTop from "@/components/ScrollToTop";

// module remixicon
import 'remixicon/fonts/remixicon.css'

const fontPoppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: '--font-poppins',
});

export const metadata = {
  title: "Company Profile",
  description: "Generated by Robby Code Project",
  icons: {
    icon: "/favicon3.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body className={`${fontPoppins.variable} antialiased`} id="home">
       
            <ScrollToTop />
            <Navbar />
            <div className="container mx-auto px-4">{children}</div>
            <Footer />
        
      </body>
    </html>
    
  );
}
