import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const fontPoppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Company Profile",
  description: "Generated by Robby Code Project",
  icons: {
    icon: "/favicon3.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fontPoppins.className} antialiased`}>
       
          <>
            <Navbar />
            <div className="container mx-auto px-4">{children}</div>
          </>
        
      </body>
    </html>
  );
}
